[package]
name = "winfetch"
version = "0.2.1"
edition = "2021"

[dependencies]
colored = "2.1"
crossterm = "0.27"
rand = "0.8"
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_System_SystemInformation",
    "Win32_System_Registry",
    "Win32_System_Console",
    "Win32_Graphics_Gdi"
] }